//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/convert/PeriodConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeConvertPeriodConverter_INCLUDE_ALL")
#ifdef OrgJodaTimeConvertPeriodConverter_RESTRICT
#define OrgJodaTimeConvertPeriodConverter_INCLUDE_ALL 0
#else
#define OrgJodaTimeConvertPeriodConverter_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeConvertPeriodConverter_RESTRICT

#if !defined (OrgJodaTimeConvertPeriodConverter_) && (OrgJodaTimeConvertPeriodConverter_INCLUDE_ALL || defined(OrgJodaTimeConvertPeriodConverter_INCLUDE))
#define OrgJodaTimeConvertPeriodConverter_

#define OrgJodaTimeConvertConverter_RESTRICT 1
#define OrgJodaTimeConvertConverter_INCLUDE 1
#include "org/joda/time/convert/Converter.h"

@class OrgJodaTimeChronology;
@class OrgJodaTimePeriodType;
@protocol OrgJodaTimeReadWritablePeriod;

@protocol OrgJodaTimeConvertPeriodConverter < OrgJodaTimeConvertConverter, NSObject, JavaObject >

- (void)setIntoWithOrgJodaTimeReadWritablePeriod:(id<OrgJodaTimeReadWritablePeriod>)period
                                          withId:(id)object
                       withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

- (OrgJodaTimePeriodType *)getPeriodTypeWithId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeConvertPeriodConverter)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeConvertPeriodConverter)

#endif

#pragma pop_macro("OrgJodaTimeConvertPeriodConverter_INCLUDE_ALL")
