//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/field/UnsupportedDurationField.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeFieldUnsupportedDurationField_INCLUDE_ALL")
#ifdef OrgJodaTimeFieldUnsupportedDurationField_RESTRICT
#define OrgJodaTimeFieldUnsupportedDurationField_INCLUDE_ALL 0
#else
#define OrgJodaTimeFieldUnsupportedDurationField_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeFieldUnsupportedDurationField_RESTRICT

#if !defined (OrgJodaTimeFieldUnsupportedDurationField_) && (OrgJodaTimeFieldUnsupportedDurationField_INCLUDE_ALL || defined(OrgJodaTimeFieldUnsupportedDurationField_INCLUDE))
#define OrgJodaTimeFieldUnsupportedDurationField_

#define OrgJodaTimeDurationField_RESTRICT 1
#define OrgJodaTimeDurationField_INCLUDE 1
#include "org/joda/time/DurationField.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"

@class OrgJodaTimeDurationFieldType;

@interface OrgJodaTimeFieldUnsupportedDurationField : OrgJodaTimeDurationField < JavaIoSerializable >

#pragma mark Public

- (jlong)addWithLong:(jlong)instant
             withInt:(jint)value;

- (jlong)addWithLong:(jlong)instant
            withLong:(jlong)value;

- (jint)compareToWithId:(OrgJodaTimeDurationField *)durationField;

- (jboolean)isEqual:(id)obj;

- (jint)getDifferenceWithLong:(jlong)minuendInstant
                     withLong:(jlong)subtrahendInstant;

- (jlong)getDifferenceAsLongWithLong:(jlong)minuendInstant
                            withLong:(jlong)subtrahendInstant;

+ (OrgJodaTimeFieldUnsupportedDurationField *)getInstanceWithOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)type;

- (jlong)getMillisWithInt:(jint)value;

- (jlong)getMillisWithInt:(jint)value
                 withLong:(jlong)instant;

- (jlong)getMillisWithLong:(jlong)value;

- (jlong)getMillisWithLong:(jlong)value
                  withLong:(jlong)instant;

- (NSString *)getName;

- (OrgJodaTimeDurationFieldType *)getType;

- (jlong)getUnitMillis;

- (jint)getValueWithLong:(jlong)duration;

- (jint)getValueWithLong:(jlong)duration
                withLong:(jlong)instant;

- (jlong)getValueAsLongWithLong:(jlong)duration;

- (jlong)getValueAsLongWithLong:(jlong)duration
                       withLong:(jlong)instant;

- (NSUInteger)hash;

- (jboolean)isPrecise;

- (jboolean)isSupported;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeFieldUnsupportedDurationField)

FOUNDATION_EXPORT OrgJodaTimeFieldUnsupportedDurationField *OrgJodaTimeFieldUnsupportedDurationField_getInstanceWithOrgJodaTimeDurationFieldType_(OrgJodaTimeDurationFieldType *type);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeFieldUnsupportedDurationField)

#endif

#pragma pop_macro("OrgJodaTimeFieldUnsupportedDurationField_INCLUDE_ALL")
