//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/northropo/Projects/paco/Shared/src/com/pacoapp/paco/shared/model2/Feedback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("Feedback_INCLUDE_ALL")
#ifdef Feedback_RESTRICT
#define Feedback_INCLUDE_ALL 0
#else
#define Feedback_INCLUDE_ALL 1
#endif
#undef Feedback_RESTRICT

#if !defined (PAFeedback_) && (Feedback_INCLUDE_ALL || defined(PAFeedback_INCLUDE))
#define PAFeedback_

#define ModelBase_RESTRICT 1
#define PAModelBase_INCLUDE 1
#include "ModelBase.h"

#define Validatable_RESTRICT 1
#define PAValidatable_INCLUDE 1
#include "Validatable.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"

@class JavaLangInteger;
@protocol PAValidator;

@interface PAFeedback : PAModelBase < PAValidatable, JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)text;

- (NSString *)getText;

- (JavaLangInteger *)getType;

- (void)setTextWithNSString:(NSString *)text;

- (void)setTypeWithJavaLangInteger:(JavaLangInteger *)type;

- (void)validateWithWithPAValidator:(id<PAValidator>)validator;

@end

J2OBJC_EMPTY_STATIC_INIT(PAFeedback)

inline jint PAFeedback_get_FEEDBACK_TYPE_STATIC_MESSAGE();
#define PAFeedback_FEEDBACK_TYPE_STATIC_MESSAGE 0
J2OBJC_STATIC_FIELD_CONSTANT(PAFeedback, FEEDBACK_TYPE_STATIC_MESSAGE, jint)

inline jint PAFeedback_get_FEEDBACK_TYPE_RETROSPECTIVE();
#define PAFeedback_FEEDBACK_TYPE_RETROSPECTIVE 1
J2OBJC_STATIC_FIELD_CONSTANT(PAFeedback, FEEDBACK_TYPE_RETROSPECTIVE, jint)

inline jint PAFeedback_get_FEEDBACK_TYPE_RESPONSIVE();
#define PAFeedback_FEEDBACK_TYPE_RESPONSIVE 2
J2OBJC_STATIC_FIELD_CONSTANT(PAFeedback, FEEDBACK_TYPE_RESPONSIVE, jint)

inline jint PAFeedback_get_FEEDBACK_TYPE_CUSTOM();
#define PAFeedback_FEEDBACK_TYPE_CUSTOM 3
J2OBJC_STATIC_FIELD_CONSTANT(PAFeedback, FEEDBACK_TYPE_CUSTOM, jint)

inline jint PAFeedback_get_FEEDBACK_TYPE_HIDE_FEEDBACK();
#define PAFeedback_FEEDBACK_TYPE_HIDE_FEEDBACK 4
J2OBJC_STATIC_FIELD_CONSTANT(PAFeedback, FEEDBACK_TYPE_HIDE_FEEDBACK, jint)

inline NSString *PAFeedback_get_DEFAULT_FEEDBACK_MSG();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PAFeedback_DEFAULT_FEEDBACK_MSG;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PAFeedback, DEFAULT_FEEDBACK_MSG, NSString *)

FOUNDATION_EXPORT void PAFeedback_initWithNSString_(PAFeedback *self, NSString *text);

FOUNDATION_EXPORT PAFeedback *new_PAFeedback_initWithNSString_(NSString *text) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PAFeedback *create_PAFeedback_initWithNSString_(NSString *text);

FOUNDATION_EXPORT void PAFeedback_init(PAFeedback *self);

FOUNDATION_EXPORT PAFeedback *new_PAFeedback_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PAFeedback *create_PAFeedback_init();

J2OBJC_TYPE_LITERAL_HEADER(PAFeedback)

@compatibility_alias ComPacoappPacoSharedModel2Feedback PAFeedback;

#endif

#pragma pop_macro("Feedback_INCLUDE_ALL")
