//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/northropo/Projects/paco/Shared/src/com/pacoapp/paco/shared/model2/PacoActionAllOthers.java
//

#include "J2ObjC_header.h"

#pragma push_macro("PacoActionAllOthers_INCLUDE_ALL")
#ifdef PacoActionAllOthers_RESTRICT
#define PacoActionAllOthers_INCLUDE_ALL 0
#else
#define PacoActionAllOthers_INCLUDE_ALL 1
#endif
#undef PacoActionAllOthers_RESTRICT

#if !defined (PAPacoActionAllOthers_) && (PacoActionAllOthers_INCLUDE_ALL || defined(PAPacoActionAllOthers_INCLUDE))
#define PAPacoActionAllOthers_

#define PacoAction_RESTRICT 1
#define PAPacoAction_INCLUDE 1
#include "PacoAction.h"

@protocol PAValidator;

@interface PAPacoActionAllOthers : PAPacoAction {
 @public
  NSString *customScript_;
}

#pragma mark Public

- (instancetype)init;

- (NSString *)getCustomScript;

- (void)setCustomScriptWithNSString:(NSString *)customScript;

- (void)validateWithWithPAValidator:(id<PAValidator>)validator;

@end

J2OBJC_EMPTY_STATIC_INIT(PAPacoActionAllOthers)

J2OBJC_FIELD_SETTER(PAPacoActionAllOthers, customScript_, NSString *)

FOUNDATION_EXPORT void PAPacoActionAllOthers_init(PAPacoActionAllOthers *self);

FOUNDATION_EXPORT PAPacoActionAllOthers *new_PAPacoActionAllOthers_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT PAPacoActionAllOthers *create_PAPacoActionAllOthers_init();

J2OBJC_TYPE_LITERAL_HEADER(PAPacoActionAllOthers)

@compatibility_alias ComPacoappPacoSharedModel2PacoActionAllOthers PAPacoActionAllOthers;

#endif

#pragma pop_macro("PacoActionAllOthers_INCLUDE_ALL")
