//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/base/BaseDuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeBaseBaseDuration_INCLUDE_ALL")
#ifdef OrgJodaTimeBaseBaseDuration_RESTRICT
#define OrgJodaTimeBaseBaseDuration_INCLUDE_ALL 0
#else
#define OrgJodaTimeBaseBaseDuration_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeBaseBaseDuration_RESTRICT

#if !defined (OrgJodaTimeBaseBaseDuration_) && (OrgJodaTimeBaseBaseDuration_INCLUDE_ALL || defined(OrgJodaTimeBaseBaseDuration_INCLUDE))
#define OrgJodaTimeBaseBaseDuration_

#define OrgJodaTimeBaseAbstractDuration_RESTRICT 1
#define OrgJodaTimeBaseAbstractDuration_INCLUDE 1
#include "org/joda/time/base/AbstractDuration.h"

#define OrgJodaTimeReadableDuration_RESTRICT 1
#define OrgJodaTimeReadableDuration_INCLUDE 1
#include "org/joda/time/ReadableDuration.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"

@class OrgJodaTimeChronology;
@class OrgJodaTimeInterval;
@class OrgJodaTimePeriod;
@class OrgJodaTimePeriodType;
@protocol OrgJodaTimeReadableInstant;

@interface OrgJodaTimeBaseBaseDuration : OrgJodaTimeBaseAbstractDuration < OrgJodaTimeReadableDuration, JavaIoSerializable >

#pragma mark Public

- (jlong)getMillis;

- (OrgJodaTimeInterval *)toIntervalFromWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)startInstant;

- (OrgJodaTimeInterval *)toIntervalToWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)endInstant;

- (OrgJodaTimePeriod *)toPeriodWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

- (OrgJodaTimePeriod *)toPeriodWithOrgJodaTimePeriodType:(OrgJodaTimePeriodType *)type;

- (OrgJodaTimePeriod *)toPeriodWithOrgJodaTimePeriodType:(OrgJodaTimePeriodType *)type
                               withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono;

- (OrgJodaTimePeriod *)toPeriodFromWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)startInstant;

- (OrgJodaTimePeriod *)toPeriodFromWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)startInstant
                                        withOrgJodaTimePeriodType:(OrgJodaTimePeriodType *)type;

- (OrgJodaTimePeriod *)toPeriodToWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)endInstant;

- (OrgJodaTimePeriod *)toPeriodToWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)endInstant
                                      withOrgJodaTimePeriodType:(OrgJodaTimePeriodType *)type;

#pragma mark Protected

- (instancetype)initWithLong:(jlong)duration;

- (instancetype)initWithLong:(jlong)startInstant
                    withLong:(jlong)endInstant;

- (instancetype)initWithId:(id)duration;

- (instancetype)initWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)start
                    withOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)end;

- (void)setMillisWithLong:(jlong)duration;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeBaseBaseDuration)

FOUNDATION_EXPORT void OrgJodaTimeBaseBaseDuration_initWithLong_(OrgJodaTimeBaseBaseDuration *self, jlong duration);

FOUNDATION_EXPORT void OrgJodaTimeBaseBaseDuration_initWithLong_withLong_(OrgJodaTimeBaseBaseDuration *self, jlong startInstant, jlong endInstant);

FOUNDATION_EXPORT void OrgJodaTimeBaseBaseDuration_initWithOrgJodaTimeReadableInstant_withOrgJodaTimeReadableInstant_(OrgJodaTimeBaseBaseDuration *self, id<OrgJodaTimeReadableInstant> start, id<OrgJodaTimeReadableInstant> end);

FOUNDATION_EXPORT void OrgJodaTimeBaseBaseDuration_initWithId_(OrgJodaTimeBaseBaseDuration *self, id duration);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeBaseBaseDuration)

#endif

#pragma pop_macro("OrgJodaTimeBaseBaseDuration_INCLUDE_ALL")
