package com.google.android.apps.paco.test;

import java.util.List;

import com.google.common.base.Joiner;

public class ExperimentTestConstants {
  
  public static final String FIXED_ESM_TITLE = "AndroidTest - Fixed, ESM";
  public static final String FIXED_ESM_TITLE_MODIFIED = "Booyah!";
   
  public static final String FIXED_ESM = "{\"title\":\"" + FIXED_ESM_TITLE + 
      "\",\"description\":\"Description\",\"informedConsentForm\":\"Informed consent text\",\"creator\":\"donti@google.com\",\"fixedDuration\":true,\"startDate\":\"2013/07/15\",\"endDate\":\"2013/07/25\",\"id\":4051,\"signalingMechanisms\":[{\"type\":\"signalSchedule\",\"id\":4052,\"scheduleType\":4,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[57600000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false}],\"schedule\":{\"type\":\"signalSchedule\",\"id\":4052,\"scheduleType\":4,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[57600000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false},\"questionsChange\":false,\"modifyDate\":\"2013/06/28\",\"inputs\":[{\"id\":4054,\"questionType\":\"question\",\"text\":\"question1\",\"mandatory\":false,\"responseType\":\"open text\",\"likertSteps\":5,\"name\":\"question1\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":false},{\"id\":4055,\"questionType\":\"question\",\"text\":\"\",\"mandatory\":false,\"responseType\":\"location\",\"likertSteps\":5,\"name\":\"question2\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":true}],\"feedback\":[{\"id\":4373,\"feedbackType\":\"display\",\"text\":\"Thanks for Participating!\"}],\"publishedUsers\":[],\"deleted\":false,\"webRecommended\":false,\"version\":3}";
  public static final String FIXED_ESM_RETITLED = "{\"title\":\"" + FIXED_ESM_TITLE_MODIFIED + 
      "\",\"description\":\"Description\",\"informedConsentForm\":\"Informed consent text\",\"creator\":\"donti@google.com\",\"fixedDuration\":true,\"startDate\":\"2013/07/15\",\"endDate\":\"2013/07/25\",\"id\":4051,\"signalingMechanisms\":[{\"type\":\"signalSchedule\",\"id\":4052,\"scheduleType\":4,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[57600000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false}],\"schedule\":{\"type\":\"signalSchedule\",\"id\":4052,\"scheduleType\":4,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[57600000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false},\"questionsChange\":false,\"modifyDate\":\"2013/06/28\",\"inputs\":[{\"id\":4054,\"questionType\":\"question\",\"text\":\"question1\",\"mandatory\":false,\"responseType\":\"open text\",\"likertSteps\":5,\"name\":\"question1\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":false},{\"id\":4055,\"questionType\":\"question\",\"text\":\"\",\"mandatory\":false,\"responseType\":\"location\",\"likertSteps\":5,\"name\":\"question2\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":true}],\"feedback\":[{\"id\":4373,\"feedbackType\":\"display\",\"text\":\"Thanks for Participating!\"}],\"publishedUsers\":[],\"deleted\":false,\"webRecommended\":false,\"version\":3}";
  public static final Long FIXED_ESM_SERVERID = Long.valueOf(4051);
  
  public static final String ONGOING_DAILY = "{\"title\":\"AndroidTest - Ongoing, Daily\",\"description\":\"Description\",\"informedConsentForm\":\"Informed Consent Text\",\"creator\":\"donti@google.com\",\"fixedDuration\":false,\"id\":4040,\"signalingMechanisms\":[{\"type\":\"signalSchedule\",\"id\":4041,\"scheduleType\":0,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[57600000,61200000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false}],\"schedule\":{\"type\":\"signalSchedule\",\"id\":4041,\"scheduleType\":0,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[57600000,61200000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false},\"questionsChange\":false,\"modifyDate\":\"2013/06/28\",\"inputs\":[{\"id\":4043,\"questionType\":\"question\",\"text\":\"question1\",\"mandatory\":false,\"responseType\":\"likert\",\"likertSteps\":5,\"name\":\"question1\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":false},{\"id\":4044,\"questionType\":\"question\",\"text\":\"question2\",\"mandatory\":false,\"responseType\":\"list\",\"likertSteps\":5,\"name\":\"question2\",\"conditional\":false,\"listChoices\":[\"choice1\",\"choice2\",\"choice3\"],\"invisibleInput\":false}],\"feedback\":[{\"id\":4138,\"feedbackType\":\"display\",\"text\":\"Thanks for Participating!\"}],\"publishedUsers\":[],\"deleted\":false,\"webRecommended\":false,\"version\":2}";
  public static final Long ONGOING_DAILY_SERVERID = Long.valueOf(4040);
  
  public static final String ONGOING_TRIGGERED = "{\"title\":\"AndroidTest - Ongoing, Triggered\",\"description\":\"Description\",\"informedConsentForm\":\"Informed Consent Text\",\"creator\":\"donti@google.com\",\"fixedDuration\":false,\"id\":4046,\"signalingMechanisms\":[{\"type\":\"trigger\",\"eventCode\":0,\"delay\":5000,\"id\":4047}],\"schedule\":{\"type\":\"signalSchedule\",\"scheduleType\":5,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false},\"questionsChange\":false,\"modifyDate\":\"2013/06/28\",\"inputs\":[{\"id\":4049,\"questionType\":\"question\",\"text\":\"question1\",\"mandatory\":false,\"responseType\":\"likert\",\"likertSteps\":5,\"name\":\"question1\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":false}],\"feedback\":[{\"id\":4142,\"feedbackType\":\"display\",\"text\":\"Thanks for Participating!\"}],\"publishedUsers\":[],\"deleted\":false,\"webRecommended\":false,\"version\":2}";
  public static final Long ONGOING_TRIGGERED_SERVERID = Long.valueOf(4046);
  
  public static final String ONGOING_WEEKLY = "{\"title\":\"AndroidTest - Ongoing, Weekly\",\"description\":\"\",\"informedConsentForm\":\"\",\"creator\":\"donti@google.com\",\"fixedDuration\":false,\"id\":4064,\"signalingMechanisms\":[{\"type\":\"signalSchedule\",\"id\":4065,\"scheduleType\":2,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[54000000],\"repeatRate\":2,\"weekDaysScheduled\":4,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false}],\"schedule\":{\"type\":\"signalSchedule\",\"id\":4065,\"scheduleType\":2,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[54000000],\"repeatRate\":2,\"weekDaysScheduled\":4,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false},\"questionsChange\":false,\"modifyDate\":\"2013/07/01\",\"inputs\":[{\"id\":4067,\"questionType\":\"question\",\"text\":\"q1\",\"mandatory\":false,\"responseType\":\"likert\",\"likertSteps\":5,\"name\":\"q1\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":false}],\"feedback\":[{\"id\":4066,\"feedbackType\":\"display\",\"text\":\"Thanks for Participating!\"}],\"publishedUsers\":[],\"deleted\":false,\"webRecommended\":false,\"version\":1}";
  public static final Long ONGOING_WEEKLY_SERVERID = Long.valueOf(4064);
  
  public static final String ONGOING_MONTHLY = "{\"title\":\"AndroidTest - Ongoing, Monthly\",\"description\":\"\",\"informedConsentForm\":\"\",\"creator\":\"donti@google.com\",\"fixedDuration\":false,\"id\":4069,\"signalingMechanisms\":[{\"type\":\"signalSchedule\",\"id\":4070,\"scheduleType\":3,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[54000000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false}],\"schedule\":{\"type\":\"signalSchedule\",\"id\":4070,\"scheduleType\":3,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[54000000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false},\"questionsChange\":false,\"modifyDate\":\"2013/07/01\",\"inputs\":[{\"id\":4072,\"questionType\":\"question\",\"text\":\"q1\",\"mandatory\":false,\"responseType\":\"likert\",\"likertSteps\":5,\"name\":\"q1\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":false}],\"feedback\":[{\"id\":4140,\"feedbackType\":\"display\",\"text\":\"Thanks for Participating!\"}],\"publishedUsers\":[],\"deleted\":false,\"webRecommended\":false,\"version\":2}";
  public static final Long ONGOING_MONTHLY_SERVERID = Long.valueOf(4069);
  
  public static final String FIXED_WEEKDAY = "{\"title\":\"AndroidTest - Fixed, Weekday\",\"description\":\"\",\"informedConsentForm\":\"\",\"creator\":\"donti@google.com\",\"fixedDuration\":true,\"startDate\":\"2013/07/01\",\"endDate\":\"2013/07/31\",\"id\":4074,\"signalingMechanisms\":[{\"type\":\"signalSchedule\",\"id\":4075,\"scheduleType\":1,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[54000000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false}],\"schedule\":{\"type\":\"signalSchedule\",\"id\":4075,\"scheduleType\":1,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[54000000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false},\"questionsChange\":false,\"modifyDate\":\"2013/07/01\",\"inputs\":[{\"id\":4077,\"questionType\":\"question\",\"text\":\"q1\",\"mandatory\":false,\"responseType\":\"likert\",\"likertSteps\":5,\"name\":\"q1\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":false}],\"feedback\":[{\"id\":4076,\"feedbackType\":\"display\",\"text\":\"Thanks for Participating!\"}],\"publishedUsers\":[],\"deleted\":false,\"webRecommended\":false,\"version\":1}";
  public static final Long FIXED_WEEKDAY_SERVERID = Long.valueOf(4074);
  
  public static final String FIXED_SELFREPORT = "{\"title\":\"AndroidTest - Fixed, Self-Report\",\"description\":\"\",\"informedConsentForm\":\"\",\"creator\":\"donti@google.com\",\"fixedDuration\":true,\"startDate\":\"2013/07/01\",\"endDate\":\"2013/07/31\",\"id\":4079,\"signalingMechanisms\":[{\"type\":\"signalSchedule\",\"id\":4080,\"scheduleType\":5,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[54000000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false}],\"schedule\":{\"type\":\"signalSchedule\",\"id\":4080,\"scheduleType\":5,\"esmFrequency\":3,\"esmPeriodInDays\":0,\"esmStartHour\":32400000,\"esmEndHour\":61200000,\"times\":[54000000],\"repeatRate\":1,\"weekDaysScheduled\":0,\"nthOfMonth\":1,\"byDayOfMonth\":true,\"dayOfMonth\":1,\"esmWeekends\":false,\"byDayOfWeek\":false},\"questionsChange\":false,\"modifyDate\":\"2013/07/01\",\"inputs\":[{\"id\":4082,\"questionType\":\"question\",\"text\":\"q1\",\"mandatory\":false,\"responseType\":\"likert\",\"likertSteps\":5,\"name\":\"q1\",\"conditional\":false,\"listChoices\":[],\"invisibleInput\":false}],\"feedback\":[{\"id\":4081,\"feedbackType\":\"display\",\"text\":\"Thanks for Participating!\"}],\"publishedUsers\":[],\"deleted\":false,\"webRecommended\":false,\"version\":1}";
  public static final Long FIXED_SELFREPORT_SERVERID = Long.valueOf(4079);
    
  public static String joinExperimentJsons(List<String> experimentJsons) {
    String experimentList = Joiner.on(",").join(experimentJsons);
    return "[" + experimentList + "]";
  }
}
