//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/northropo/Projects/paco/Shared/src/com/pacoapp/paco/shared/model2/ActionTrigger.java
//

#include "J2ObjC_header.h"

#pragma push_macro("ActionTrigger_INCLUDE_ALL")
#ifdef ActionTrigger_RESTRICT
#define ActionTrigger_INCLUDE_ALL 0
#else
#define ActionTrigger_INCLUDE_ALL 1
#endif
#undef ActionTrigger_RESTRICT

#if !defined (PAActionTrigger_) && (ActionTrigger_INCLUDE_ALL || defined(PAActionTrigger_INCLUDE))
#define PAActionTrigger_

#define ModelBase_RESTRICT 1
#define PAModelBase_INCLUDE 1
#include "ModelBase.h"

#define Validatable_RESTRICT 1
#define PAValidatable_INCLUDE 1
#include "Validatable.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"

@class JavaLangInteger;
@class JavaLangLong;
@class PAPacoAction;
@protocol JavaUtilList;
@protocol PAValidator;

@interface PAActionTrigger : PAModelBase < PAValidatable, JavaIoSerializable > {
 @public
  NSString *type_;
  id<JavaUtilList> actions_;
}

#pragma mark Public

- (instancetype)init;

- (PAPacoAction *)getActionByIdWithJavaLangInteger:(JavaLangInteger *)id_;

- (id<JavaUtilList>)getActions;

- (JavaLangLong *)getId;

- (NSString *)getType;

- (void)setActionsWithJavaUtilList:(id<JavaUtilList>)triggerActions;

- (void)setIdWithJavaLangLong:(JavaLangLong *)id_;

- (void)setTypeWithNSString:(NSString *)type;

- (void)validateActionsWithPAValidator:(id<PAValidator>)validator;

- (void)validateWithWithPAValidator:(id<PAValidator>)validator;

@end

J2OBJC_EMPTY_STATIC_INIT(PAActionTrigger)

J2OBJC_FIELD_SETTER(PAActionTrigger, type_, NSString *)
J2OBJC_FIELD_SETTER(PAActionTrigger, actions_, id<JavaUtilList>)

inline NSString *PAActionTrigger_get_INTERRUPT_TRIGGER_TYPE_SPECIFIER();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PAActionTrigger_INTERRUPT_TRIGGER_TYPE_SPECIFIER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PAActionTrigger, INTERRUPT_TRIGGER_TYPE_SPECIFIER, NSString *)

inline NSString *PAActionTrigger_get_SCHEDULE_TRIGGER_TYPE_SPECIFIER();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *PAActionTrigger_SCHEDULE_TRIGGER_TYPE_SPECIFIER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(PAActionTrigger, SCHEDULE_TRIGGER_TYPE_SPECIFIER, NSString *)

FOUNDATION_EXPORT void PAActionTrigger_init(PAActionTrigger *self);

J2OBJC_TYPE_LITERAL_HEADER(PAActionTrigger)

@compatibility_alias ComPacoappPacoSharedModel2ActionTrigger PAActionTrigger;

#endif

#pragma pop_macro("ActionTrigger_INCLUDE_ALL")
