//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/northropo/Projects/paco/Shared/src/com/pacoapp/paco/shared/model2/ListMaker.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "ListMaker.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@implementation PAListMaker

+ (id<JavaUtilList>)paramOrNewListWithJavaUtilList:(id<JavaUtilList>)list
                                      withIOSClass:(IOSClass *)clazz {
  return PAListMaker_paramOrNewListWithJavaUtilList_withIOSClass_(list, clazz);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  PAListMaker_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "paramOrNewListWithJavaUtilList:withIOSClass:", "paramOrNewList", "Ljava.util.List;", 0x9, NULL, "<T:Ljava/lang/Object;>(Ljava/util/List<TT;>;Ljava/lang/Class<TT;>;)Ljava/util/List<TT;>;" },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcClassInfo _PAListMaker = { 2, "ListMaker", "com.pacoapp.paco.shared.model2", NULL, 0x1, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_PAListMaker;
}

@end

id<JavaUtilList> PAListMaker_paramOrNewListWithJavaUtilList_withIOSClass_(id<JavaUtilList> list, IOSClass *clazz) {
  PAListMaker_initialize();
  if (list != nil) {
    return list;
  }
  list = new_JavaUtilArrayList_init();
  return list;
}

void PAListMaker_init(PAListMaker *self) {
  NSObject_init(self);
}

PAListMaker *new_PAListMaker_init() {
  PAListMaker *self = [PAListMaker alloc];
  PAListMaker_init(self);
  return self;
}

PAListMaker *create_PAListMaker_init() {
  return new_PAListMaker_init();
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PAListMaker)
