//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/northropo/Projects/paco/Shared/src/com/pacoapp/paco/shared/model2/ValidationMessage.java
//

#include "J2ObjC_source.h"
#include "ValidationMessage.h"
#include "Validator.h"

@interface PAValidationMessage () {
 @public
  jint importance_;
  NSString *msg_;
}

- (NSString *)importanceString;

@end

J2OBJC_FIELD_SETTER(PAValidationMessage, msg_, NSString *)

__attribute__((unused)) static NSString *PAValidationMessage_importanceString(PAValidationMessage *self);

@implementation PAValidationMessage

- (instancetype)initWithNSString:(NSString *)msg
                         withInt:(jint)importance {
  PAValidationMessage_initWithNSString_withInt_(self, msg, importance);
  return self;
}

- (jint)getImportance {
  return importance_;
}

- (void)setImportanceWithInt:(jint)importance {
  self->importance_ = importance;
}

- (NSString *)getMsg {
  return msg_;
}

- (void)setMsgWithNSString:(NSString *)msg {
  self->msg_ = msg;
}

- (NSString *)description {
  return JreStrcat("$$$", PAValidationMessage_importanceString(self), @": ", msg_);
}

- (NSString *)importanceString {
  return PAValidationMessage_importanceString(self);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:", "ValidationMessage", NULL, 0x1, NULL, NULL },
    { "getImportance", NULL, "I", 0x1, NULL, NULL },
    { "setImportanceWithInt:", "setImportance", "V", 0x1, NULL, NULL },
    { "getMsg", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "setMsgWithNSString:", "setMsg", "V", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "importanceString", NULL, "Ljava.lang.String;", 0x2, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "importance_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "msg_", NULL, 0x2, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _PAValidationMessage = { 2, "ValidationMessage", "com.pacoapp.paco.shared.model2", NULL, 0x1, 7, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_PAValidationMessage;
}

@end

void PAValidationMessage_initWithNSString_withInt_(PAValidationMessage *self, NSString *msg, jint importance) {
  NSObject_init(self);
  self->msg_ = msg;
  self->importance_ = importance;
}

PAValidationMessage *new_PAValidationMessage_initWithNSString_withInt_(NSString *msg, jint importance) {
  PAValidationMessage *self = [PAValidationMessage alloc];
  PAValidationMessage_initWithNSString_withInt_(self, msg, importance);
  return self;
}

PAValidationMessage *create_PAValidationMessage_initWithNSString_withInt_(NSString *msg, jint importance) {
  return new_PAValidationMessage_initWithNSString_withInt_(msg, importance);
}

NSString *PAValidationMessage_importanceString(PAValidationMessage *self) {
  switch (self->importance_) {
    case PAValidator_MANDATORY:
    return @"ERROR";
    case PAValidator_OPTIONAL:
    return @"WARNING";
    default:
    return @"";
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(PAValidationMessage)
