//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/base/AbstractDuration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeBaseAbstractDuration_INCLUDE_ALL")
#ifdef OrgJodaTimeBaseAbstractDuration_RESTRICT
#define OrgJodaTimeBaseAbstractDuration_INCLUDE_ALL 0
#else
#define OrgJodaTimeBaseAbstractDuration_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeBaseAbstractDuration_RESTRICT

#if !defined (OrgJodaTimeBaseAbstractDuration_) && (OrgJodaTimeBaseAbstractDuration_INCLUDE_ALL || defined(OrgJodaTimeBaseAbstractDuration_INCLUDE))
#define OrgJodaTimeBaseAbstractDuration_

#define OrgJodaTimeReadableDuration_RESTRICT 1
#define OrgJodaTimeReadableDuration_INCLUDE 1
#include "org/joda/time/ReadableDuration.h"

@class OrgJodaTimeDuration;
@class OrgJodaTimePeriod;

@interface OrgJodaTimeBaseAbstractDuration : NSObject < OrgJodaTimeReadableDuration >

#pragma mark Public

- (jint)compareToWithId:(id<OrgJodaTimeReadableDuration>)other;

- (jboolean)isEqual:(id)duration;

- (NSUInteger)hash;

- (jboolean)isEqualWithOrgJodaTimeReadableDuration:(id<OrgJodaTimeReadableDuration>)duration;

- (jboolean)isLongerThanWithOrgJodaTimeReadableDuration:(id<OrgJodaTimeReadableDuration>)duration;

- (jboolean)isShorterThanWithOrgJodaTimeReadableDuration:(id<OrgJodaTimeReadableDuration>)duration;

- (OrgJodaTimeDuration *)toDuration;

- (OrgJodaTimePeriod *)toPeriod;

- (NSString *)description;

#pragma mark Protected

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeBaseAbstractDuration)

FOUNDATION_EXPORT void OrgJodaTimeBaseAbstractDuration_init(OrgJodaTimeBaseAbstractDuration *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeBaseAbstractDuration)

#endif

#pragma pop_macro("OrgJodaTimeBaseAbstractDuration_INCLUDE_ALL")
