//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/chrono/ISOYearOfEraDateTimeField.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeChronoISOYearOfEraDateTimeField_INCLUDE_ALL")
#ifdef OrgJodaTimeChronoISOYearOfEraDateTimeField_RESTRICT
#define OrgJodaTimeChronoISOYearOfEraDateTimeField_INCLUDE_ALL 0
#else
#define OrgJodaTimeChronoISOYearOfEraDateTimeField_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeChronoISOYearOfEraDateTimeField_RESTRICT

#if !defined (OrgJodaTimeChronoISOYearOfEraDateTimeField_) && (OrgJodaTimeChronoISOYearOfEraDateTimeField_INCLUDE_ALL || defined(OrgJodaTimeChronoISOYearOfEraDateTimeField_INCLUDE))
#define OrgJodaTimeChronoISOYearOfEraDateTimeField_

#define OrgJodaTimeFieldDecoratedDateTimeField_RESTRICT 1
#define OrgJodaTimeFieldDecoratedDateTimeField_INCLUDE 1
#include "org/joda/time/field/DecoratedDateTimeField.h"

@class IOSIntArray;
@class OrgJodaTimeDateTimeField;
@class OrgJodaTimeDurationField;
@protocol OrgJodaTimeReadablePartial;

@interface OrgJodaTimeChronoISOYearOfEraDateTimeField : OrgJodaTimeFieldDecoratedDateTimeField

#pragma mark Public

- (jlong)addWithLong:(jlong)instant
             withInt:(jint)years;

- (jlong)addWithLong:(jlong)instant
            withLong:(jlong)years;

- (jlong)addWrapFieldWithLong:(jlong)instant
                      withInt:(jint)years;

- (IOSIntArray *)addWrapFieldWithOrgJodaTimeReadablePartial:(id<OrgJodaTimeReadablePartial>)instant
                                                    withInt:(jint)fieldIndex
                                               withIntArray:(IOSIntArray *)values
                                                    withInt:(jint)years;

- (jint)getWithLong:(jlong)instant;

- (jint)getDifferenceWithLong:(jlong)minuendInstant
                     withLong:(jlong)subtrahendInstant;

- (jlong)getDifferenceAsLongWithLong:(jlong)minuendInstant
                            withLong:(jlong)subtrahendInstant;

- (jint)getMaximumValue;

- (jint)getMinimumValue;

- (OrgJodaTimeDurationField *)getRangeDurationField;

- (jlong)remainderWithLong:(jlong)instant;

- (jlong)roundCeilingWithLong:(jlong)instant;

- (jlong)roundFloorWithLong:(jlong)instant;

- (jlong)setWithLong:(jlong)instant
             withInt:(jint)year;

@end

J2OBJC_STATIC_INIT(OrgJodaTimeChronoISOYearOfEraDateTimeField)

inline OrgJodaTimeDateTimeField *OrgJodaTimeChronoISOYearOfEraDateTimeField_get_INSTANCE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJodaTimeDateTimeField *OrgJodaTimeChronoISOYearOfEraDateTimeField_INSTANCE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJodaTimeChronoISOYearOfEraDateTimeField, INSTANCE, OrgJodaTimeDateTimeField *)

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeChronoISOYearOfEraDateTimeField)

#endif

#pragma pop_macro("OrgJodaTimeChronoISOYearOfEraDateTimeField_INCLUDE_ALL")
