//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/tz/NameProvider.java
//

#include "J2ObjC_source.h"
#include "java/util/Locale.h"
#include "org/joda/time/tz/NameProvider.h"

@interface OrgJodaTimeTzNameProvider : NSObject

@end

@implementation OrgJodaTimeTzNameProvider

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getShortNameWithJavaUtilLocale:withNSString:withNSString:", "getShortName", "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getNameWithJavaUtilLocale:withNSString:withNSString:", "getName", "Ljava.lang.String;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgJodaTimeTzNameProvider = { 2, "NameProvider", "org.joda.time.tz", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgJodaTimeTzNameProvider;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaTimeTzNameProvider)
