//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/tz/FixedDateTimeZone.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeTzFixedDateTimeZone_INCLUDE_ALL")
#ifdef OrgJodaTimeTzFixedDateTimeZone_RESTRICT
#define OrgJodaTimeTzFixedDateTimeZone_INCLUDE_ALL 0
#else
#define OrgJodaTimeTzFixedDateTimeZone_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeTzFixedDateTimeZone_RESTRICT

#if !defined (OrgJodaTimeTzFixedDateTimeZone_) && (OrgJodaTimeTzFixedDateTimeZone_INCLUDE_ALL || defined(OrgJodaTimeTzFixedDateTimeZone_INCLUDE))
#define OrgJodaTimeTzFixedDateTimeZone_

#define OrgJodaTimeDateTimeZone_RESTRICT 1
#define OrgJodaTimeDateTimeZone_INCLUDE 1
#include "org/joda/time/DateTimeZone.h"

@class JavaUtilTimeZone;

@interface OrgJodaTimeTzFixedDateTimeZone : OrgJodaTimeDateTimeZone

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)id_
                    withNSString:(NSString *)nameKey
                         withInt:(jint)wallOffset
                         withInt:(jint)standardOffset;

- (jboolean)isEqual:(id)obj;

- (NSString *)getNameKeyWithLong:(jlong)instant;

- (jint)getOffsetWithLong:(jlong)instant;

- (jint)getOffsetFromLocalWithLong:(jlong)instantLocal;

- (jint)getStandardOffsetWithLong:(jlong)instant;

- (NSUInteger)hash;

- (jboolean)isFixed;

- (jlong)nextTransitionWithLong:(jlong)instant;

- (jlong)previousTransitionWithLong:(jlong)instant;

- (JavaUtilTimeZone *)toTimeZone;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeTzFixedDateTimeZone)

FOUNDATION_EXPORT void OrgJodaTimeTzFixedDateTimeZone_initWithNSString_withNSString_withInt_withInt_(OrgJodaTimeTzFixedDateTimeZone *self, NSString *id_, NSString *nameKey, jint wallOffset, jint standardOffset);

FOUNDATION_EXPORT OrgJodaTimeTzFixedDateTimeZone *new_OrgJodaTimeTzFixedDateTimeZone_initWithNSString_withNSString_withInt_withInt_(NSString *id_, NSString *nameKey, jint wallOffset, jint standardOffset) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeTzFixedDateTimeZone *create_OrgJodaTimeTzFixedDateTimeZone_initWithNSString_withNSString_withInt_withInt_(NSString *id_, NSString *nameKey, jint wallOffset, jint standardOffset);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeTzFixedDateTimeZone)

#endif

#pragma pop_macro("OrgJodaTimeTzFixedDateTimeZone_INCLUDE_ALL")
