//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/ReadWritablePeriod.java
//

#include "J2ObjC_source.h"
#include "org/joda/time/DurationFieldType.h"
#include "org/joda/time/ReadWritablePeriod.h"
#include "org/joda/time/ReadableInterval.h"
#include "org/joda/time/ReadablePeriod.h"

@interface OrgJodaTimeReadWritablePeriod : NSObject

@end

@implementation OrgJodaTimeReadWritablePeriod

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "clear", NULL, "V", 0x401, NULL, NULL },
    { "setValueWithInt:withInt:", "setValue", "V", 0x401, NULL, NULL },
    { "setWithOrgJodaTimeDurationFieldType:withInt:", "set", "V", 0x401, NULL, NULL },
    { "setPeriodWithOrgJodaTimeReadablePeriod:", "setPeriod", "V", 0x401, NULL, NULL },
    { "setPeriodWithInt:withInt:withInt:withInt:withInt:withInt:withInt:withInt:", "setPeriod", "V", 0x401, NULL, NULL },
    { "setPeriodWithOrgJodaTimeReadableInterval:", "setPeriod", "V", 0x401, NULL, NULL },
    { "addWithOrgJodaTimeDurationFieldType:withInt:", "add", "V", 0x401, NULL, NULL },
    { "addWithOrgJodaTimeReadablePeriod:", "add", "V", 0x401, NULL, NULL },
    { "addWithInt:withInt:withInt:withInt:withInt:withInt:withInt:withInt:", "add", "V", 0x401, NULL, NULL },
    { "addWithOrgJodaTimeReadableInterval:", "add", "V", 0x401, NULL, NULL },
    { "setYearsWithInt:", "setYears", "V", 0x401, NULL, NULL },
    { "addYearsWithInt:", "addYears", "V", 0x401, NULL, NULL },
    { "setMonthsWithInt:", "setMonths", "V", 0x401, NULL, NULL },
    { "addMonthsWithInt:", "addMonths", "V", 0x401, NULL, NULL },
    { "setWeeksWithInt:", "setWeeks", "V", 0x401, NULL, NULL },
    { "addWeeksWithInt:", "addWeeks", "V", 0x401, NULL, NULL },
    { "setDaysWithInt:", "setDays", "V", 0x401, NULL, NULL },
    { "addDaysWithInt:", "addDays", "V", 0x401, NULL, NULL },
    { "setHoursWithInt:", "setHours", "V", 0x401, NULL, NULL },
    { "addHoursWithInt:", "addHours", "V", 0x401, NULL, NULL },
    { "setMinutesWithInt:", "setMinutes", "V", 0x401, NULL, NULL },
    { "addMinutesWithInt:", "addMinutes", "V", 0x401, NULL, NULL },
    { "setSecondsWithInt:", "setSeconds", "V", 0x401, NULL, NULL },
    { "addSecondsWithInt:", "addSeconds", "V", 0x401, NULL, NULL },
    { "setMillisWithInt:", "setMillis", "V", 0x401, NULL, NULL },
    { "addMillisWithInt:", "addMillis", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _OrgJodaTimeReadWritablePeriod = { 2, "ReadWritablePeriod", "org.joda.time", NULL, 0x609, 26, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgJodaTimeReadWritablePeriod;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJodaTimeReadWritablePeriod)
