//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/YearMonth.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IndexOutOfBoundsException.h"
#include "java/lang/NullPointerException.h"
#include "java/util/Calendar.h"
#include "java/util/Date.h"
#include "java/util/Locale.h"
#include "org/joda/convert/FromString.h"
#include "org/joda/convert/ToString.h"
#include "org/joda/time/Chronology.h"
#include "org/joda/time/DateTime.h"
#include "org/joda/time/DateTimeField.h"
#include "org/joda/time/DateTimeFieldType.h"
#include "org/joda/time/DateTimeUtils.h"
#include "org/joda/time/DateTimeZone.h"
#include "org/joda/time/DurationFieldType.h"
#include "org/joda/time/Interval.h"
#include "org/joda/time/LocalDate.h"
#include "org/joda/time/ReadablePartial.h"
#include "org/joda/time/ReadablePeriod.h"
#include "org/joda/time/YearMonth.h"
#include "org/joda/time/base/AbstractPartial.h"
#include "org/joda/time/base/BasePartial.h"
#include "org/joda/time/chrono/ISOChronology.h"
#include "org/joda/time/field/AbstractPartialFieldProperty.h"
#include "org/joda/time/field/FieldUtils.h"
#include "org/joda/time/format/DateTimeFormat.h"
#include "org/joda/time/format/DateTimeFormatter.h"
#include "org/joda/time/format/ISODateTimeFormat.h"

@interface OrgJodaTimeYearMonth ()

- (id)readResolve;

@end

inline jlong OrgJodaTimeYearMonth_get_serialVersionUID();
#define OrgJodaTimeYearMonth_serialVersionUID 797544782896179LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgJodaTimeYearMonth, serialVersionUID, jlong)

inline IOSObjectArray *OrgJodaTimeYearMonth_get_FIELD_TYPES();
static IOSObjectArray *OrgJodaTimeYearMonth_FIELD_TYPES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJodaTimeYearMonth, FIELD_TYPES, IOSObjectArray *)

@interface OrgJodaTimeYearMonth_Property () {
 @public
  OrgJodaTimeYearMonth *iBase_;
  jint iFieldIndex_;
}

@end

J2OBJC_FIELD_SETTER(OrgJodaTimeYearMonth_Property, iBase_, OrgJodaTimeYearMonth *)

inline jlong OrgJodaTimeYearMonth_Property_get_serialVersionUID();
#define OrgJodaTimeYearMonth_Property_serialVersionUID 5727734012190224363LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgJodaTimeYearMonth_Property, serialVersionUID, jlong)

J2OBJC_INITIALIZED_DEFN(OrgJodaTimeYearMonth)

@implementation OrgJodaTimeYearMonth

+ (OrgJodaTimeYearMonth *)now {
  return OrgJodaTimeYearMonth_now();
}

+ (OrgJodaTimeYearMonth *)nowWithOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)zone {
  return OrgJodaTimeYearMonth_nowWithOrgJodaTimeDateTimeZone_(zone);
}

+ (OrgJodaTimeYearMonth *)nowWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)chronology {
  return OrgJodaTimeYearMonth_nowWithOrgJodaTimeChronology_(chronology);
}

+ (OrgJodaTimeYearMonth *)parseWithNSString:(NSString *)str {
  return OrgJodaTimeYearMonth_parseWithNSString_(str);
}

+ (OrgJodaTimeYearMonth *)parseWithNSString:(NSString *)str
     withOrgJodaTimeFormatDateTimeFormatter:(OrgJodaTimeFormatDateTimeFormatter *)formatter {
  return OrgJodaTimeYearMonth_parseWithNSString_withOrgJodaTimeFormatDateTimeFormatter_(str, formatter);
}

+ (OrgJodaTimeYearMonth *)fromCalendarFieldsWithJavaUtilCalendar:(JavaUtilCalendar *)calendar {
  return OrgJodaTimeYearMonth_fromCalendarFieldsWithJavaUtilCalendar_(calendar);
}

+ (OrgJodaTimeYearMonth *)fromDateFieldsWithJavaUtilDate:(JavaUtilDate *)date {
  return OrgJodaTimeYearMonth_fromDateFieldsWithJavaUtilDate_(date);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgJodaTimeYearMonth_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)zone {
  OrgJodaTimeYearMonth_initWithOrgJodaTimeDateTimeZone_(self, zone);
  return self;
}

- (instancetype)initWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)chronology {
  OrgJodaTimeYearMonth_initWithOrgJodaTimeChronology_(self, chronology);
  return self;
}

- (instancetype)initWithLong:(jlong)instant {
  OrgJodaTimeYearMonth_initWithLong_(self, instant);
  return self;
}

- (instancetype)initWithLong:(jlong)instant
   withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chronology {
  OrgJodaTimeYearMonth_initWithLong_withOrgJodaTimeChronology_(self, instant, chronology);
  return self;
}

- (instancetype)initWithId:(id)instant {
  OrgJodaTimeYearMonth_initWithId_(self, instant);
  return self;
}

- (instancetype)initWithId:(id)instant
 withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chronology {
  OrgJodaTimeYearMonth_initWithId_withOrgJodaTimeChronology_(self, instant, chronology);
  return self;
}

- (instancetype)initWithInt:(jint)year
                    withInt:(jint)monthOfYear {
  OrgJodaTimeYearMonth_initWithInt_withInt_(self, year, monthOfYear);
  return self;
}

- (instancetype)initWithInt:(jint)year
                    withInt:(jint)monthOfYear
  withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chronology {
  OrgJodaTimeYearMonth_initWithInt_withInt_withOrgJodaTimeChronology_(self, year, monthOfYear, chronology);
  return self;
}

- (instancetype)initWithOrgJodaTimeYearMonth:(OrgJodaTimeYearMonth *)partial
                                withIntArray:(IOSIntArray *)values {
  OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(self, partial, values);
  return self;
}

- (instancetype)initWithOrgJodaTimeYearMonth:(OrgJodaTimeYearMonth *)partial
                   withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono {
  OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withOrgJodaTimeChronology_(self, partial, chrono);
  return self;
}

- (id)readResolve {
  if ([((OrgJodaTimeDateTimeZone *) nil_chk(JreLoadStatic(OrgJodaTimeDateTimeZone, UTC))) isEqual:[((OrgJodaTimeChronology *) nil_chk([self getChronology])) getZone]] == false) {
    return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withOrgJodaTimeChronology_(self, [((OrgJodaTimeChronology *) nil_chk([self getChronology])) withUTC]);
  }
  return self;
}

- (jint)size {
  return 2;
}

- (OrgJodaTimeDateTimeField *)getFieldWithInt:(jint)index
                    withOrgJodaTimeChronology:(OrgJodaTimeChronology *)chrono {
  switch (index) {
    case OrgJodaTimeYearMonth_YEAR:
    return [((OrgJodaTimeChronology *) nil_chk(chrono)) year];
    case OrgJodaTimeYearMonth_MONTH_OF_YEAR:
    return [((OrgJodaTimeChronology *) nil_chk(chrono)) monthOfYear];
    default:
    @throw create_JavaLangIndexOutOfBoundsException_initWithNSString_(JreStrcat("$I", @"Invalid index: ", index));
  }
}

- (OrgJodaTimeDateTimeFieldType *)getFieldTypeWithInt:(jint)index {
  return IOSObjectArray_Get(nil_chk(OrgJodaTimeYearMonth_FIELD_TYPES), index);
}

- (IOSObjectArray *)getFieldTypes {
  return [((IOSObjectArray *) nil_chk(OrgJodaTimeYearMonth_FIELD_TYPES)) clone];
}

- (OrgJodaTimeYearMonth *)withChronologyRetainFieldsWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)newChronology {
  newChronology = OrgJodaTimeDateTimeUtils_getChronologyWithOrgJodaTimeChronology_(newChronology);
  newChronology = [((OrgJodaTimeChronology *) nil_chk(newChronology)) withUTC];
  if (newChronology == [self getChronology]) {
    return self;
  }
  else {
    OrgJodaTimeYearMonth *newYearMonth = create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withOrgJodaTimeChronology_(self, newChronology);
    [((OrgJodaTimeChronology *) nil_chk(newChronology)) validateWithOrgJodaTimeReadablePartial:newYearMonth withIntArray:[self getValues]];
    return newYearMonth;
  }
}

- (OrgJodaTimeYearMonth *)withFieldWithOrgJodaTimeDateTimeFieldType:(OrgJodaTimeDateTimeFieldType *)fieldType
                                                            withInt:(jint)value {
  jint index = [self indexOfSupportedWithOrgJodaTimeDateTimeFieldType:fieldType];
  if (value == [self getValueWithInt:index]) {
    return self;
  }
  IOSIntArray *newValues = [self getValues];
  newValues = [((OrgJodaTimeDateTimeField *) nil_chk([self getFieldWithInt:index])) setWithOrgJodaTimeReadablePartial:self withInt:index withIntArray:newValues withInt:value];
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(self, newValues);
}

- (OrgJodaTimeYearMonth *)withFieldAddedWithOrgJodaTimeDurationFieldType:(OrgJodaTimeDurationFieldType *)fieldType
                                                                 withInt:(jint)amount {
  jint index = [self indexOfSupportedWithOrgJodaTimeDurationFieldType:fieldType];
  if (amount == 0) {
    return self;
  }
  IOSIntArray *newValues = [self getValues];
  newValues = [((OrgJodaTimeDateTimeField *) nil_chk([self getFieldWithInt:index])) addWithOrgJodaTimeReadablePartial:self withInt:index withIntArray:newValues withInt:amount];
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(self, newValues);
}

- (OrgJodaTimeYearMonth *)withPeriodAddedWithOrgJodaTimeReadablePeriod:(id<OrgJodaTimeReadablePeriod>)period
                                                               withInt:(jint)scalar {
  if (period == nil || scalar == 0) {
    return self;
  }
  IOSIntArray *newValues = [self getValues];
  for (jint i = 0; i < [((id<OrgJodaTimeReadablePeriod>) nil_chk(period)) size]; i++) {
    OrgJodaTimeDurationFieldType *fieldType = [period getFieldTypeWithInt:i];
    jint index = [self indexOfWithOrgJodaTimeDurationFieldType:fieldType];
    if (index >= 0) {
      newValues = [((OrgJodaTimeDateTimeField *) nil_chk([self getFieldWithInt:index])) addWithOrgJodaTimeReadablePartial:self withInt:index withIntArray:newValues withInt:OrgJodaTimeFieldFieldUtils_safeMultiplyWithInt_withInt_([period getValueWithInt:i], scalar)];
    }
  }
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(self, newValues);
}

- (OrgJodaTimeYearMonth *)plusWithOrgJodaTimeReadablePeriod:(id<OrgJodaTimeReadablePeriod>)period {
  return [self withPeriodAddedWithOrgJodaTimeReadablePeriod:period withInt:1];
}

- (OrgJodaTimeYearMonth *)plusYearsWithInt:(jint)years {
  return [self withFieldAddedWithOrgJodaTimeDurationFieldType:OrgJodaTimeDurationFieldType_years() withInt:years];
}

- (OrgJodaTimeYearMonth *)plusMonthsWithInt:(jint)months {
  return [self withFieldAddedWithOrgJodaTimeDurationFieldType:OrgJodaTimeDurationFieldType_months() withInt:months];
}

- (OrgJodaTimeYearMonth *)minusWithOrgJodaTimeReadablePeriod:(id<OrgJodaTimeReadablePeriod>)period {
  return [self withPeriodAddedWithOrgJodaTimeReadablePeriod:period withInt:-1];
}

- (OrgJodaTimeYearMonth *)minusYearsWithInt:(jint)years {
  return [self withFieldAddedWithOrgJodaTimeDurationFieldType:OrgJodaTimeDurationFieldType_years() withInt:OrgJodaTimeFieldFieldUtils_safeNegateWithInt_(years)];
}

- (OrgJodaTimeYearMonth *)minusMonthsWithInt:(jint)months {
  return [self withFieldAddedWithOrgJodaTimeDurationFieldType:OrgJodaTimeDurationFieldType_months() withInt:OrgJodaTimeFieldFieldUtils_safeNegateWithInt_(months)];
}

- (OrgJodaTimeLocalDate *)toLocalDateWithInt:(jint)dayOfMonth {
  return create_OrgJodaTimeLocalDate_initWithInt_withInt_withInt_withOrgJodaTimeChronology_([self getYear], [self getMonthOfYear], dayOfMonth, [self getChronology]);
}

- (OrgJodaTimeInterval *)toInterval {
  return [self toIntervalWithOrgJodaTimeDateTimeZone:nil];
}

- (OrgJodaTimeInterval *)toIntervalWithOrgJodaTimeDateTimeZone:(OrgJodaTimeDateTimeZone *)zone {
  zone = OrgJodaTimeDateTimeUtils_getZoneWithOrgJodaTimeDateTimeZone_(zone);
  OrgJodaTimeDateTime *start = [((OrgJodaTimeLocalDate *) nil_chk([self toLocalDateWithInt:1])) toDateTimeAtStartOfDayWithOrgJodaTimeDateTimeZone:zone];
  OrgJodaTimeDateTime *end = [((OrgJodaTimeLocalDate *) nil_chk([((OrgJodaTimeYearMonth *) nil_chk([self plusMonthsWithInt:1])) toLocalDateWithInt:1])) toDateTimeAtStartOfDayWithOrgJodaTimeDateTimeZone:zone];
  return create_OrgJodaTimeInterval_initWithOrgJodaTimeReadableInstant_withOrgJodaTimeReadableInstant_(start, end);
}

- (jint)getYear {
  return [self getValueWithInt:OrgJodaTimeYearMonth_YEAR];
}

- (jint)getMonthOfYear {
  return [self getValueWithInt:OrgJodaTimeYearMonth_MONTH_OF_YEAR];
}

- (OrgJodaTimeYearMonth *)withYearWithInt:(jint)year {
  IOSIntArray *newValues = [self getValues];
  newValues = [((OrgJodaTimeDateTimeField *) nil_chk([((OrgJodaTimeChronology *) nil_chk([self getChronology])) year])) setWithOrgJodaTimeReadablePartial:self withInt:OrgJodaTimeYearMonth_YEAR withIntArray:newValues withInt:year];
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(self, newValues);
}

- (OrgJodaTimeYearMonth *)withMonthOfYearWithInt:(jint)monthOfYear {
  IOSIntArray *newValues = [self getValues];
  newValues = [((OrgJodaTimeDateTimeField *) nil_chk([((OrgJodaTimeChronology *) nil_chk([self getChronology])) monthOfYear])) setWithOrgJodaTimeReadablePartial:self withInt:OrgJodaTimeYearMonth_MONTH_OF_YEAR withIntArray:newValues withInt:monthOfYear];
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(self, newValues);
}

- (OrgJodaTimeYearMonth_Property *)propertyWithOrgJodaTimeDateTimeFieldType:(OrgJodaTimeDateTimeFieldType *)type {
  return create_OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(self, [self indexOfSupportedWithOrgJodaTimeDateTimeFieldType:type]);
}

- (OrgJodaTimeYearMonth_Property *)year {
  return create_OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(self, OrgJodaTimeYearMonth_YEAR);
}

- (OrgJodaTimeYearMonth_Property *)monthOfYear {
  return create_OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(self, OrgJodaTimeYearMonth_MONTH_OF_YEAR);
}

- (NSString *)description {
  return [((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(OrgJodaTimeFormatISODateTimeFormat_yearMonth())) printWithOrgJodaTimeReadablePartial:self];
}

- (NSString *)toStringWithNSString:(NSString *)pattern {
  if (pattern == nil) {
    return [self description];
  }
  return [((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(OrgJodaTimeFormatDateTimeFormat_forPatternWithNSString_(pattern))) printWithOrgJodaTimeReadablePartial:self];
}

- (NSString *)toStringWithNSString:(NSString *)pattern
                withJavaUtilLocale:(JavaUtilLocale *)locale {
  if (pattern == nil) {
    return [self description];
  }
  return [((OrgJodaTimeFormatDateTimeFormatter *) nil_chk([((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(OrgJodaTimeFormatDateTimeFormat_forPatternWithNSString_(pattern))) withLocaleWithJavaUtilLocale:locale])) printWithOrgJodaTimeReadablePartial:self];
}

+ (void)initialize {
  if (self == [OrgJodaTimeYearMonth class]) {
    JreStrongAssignAndConsume(&OrgJodaTimeYearMonth_FIELD_TYPES, [IOSObjectArray newArrayWithObjects:(id[]){ OrgJodaTimeDateTimeFieldType_year(), OrgJodaTimeDateTimeFieldType_monthOfYear() } count:2 type:OrgJodaTimeDateTimeFieldType_class_()]);
    J2OBJC_SET_INITIALIZED(OrgJodaTimeYearMonth)
  }
}

+ (IOSObjectArray *)__annotations_parseWithNSString_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJodaConvertFromString alloc] init] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_toString {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[OrgJodaConvertToString alloc] init] autorelease] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "now", NULL, "Lorg.joda.time.YearMonth;", 0x9, NULL, NULL },
    { "nowWithOrgJodaTimeDateTimeZone:", "now", "Lorg.joda.time.YearMonth;", 0x9, NULL, NULL },
    { "nowWithOrgJodaTimeChronology:", "now", "Lorg.joda.time.YearMonth;", 0x9, NULL, NULL },
    { "parseWithNSString:", "parse", "Lorg.joda.time.YearMonth;", 0x9, NULL, NULL },
    { "parseWithNSString:withOrgJodaTimeFormatDateTimeFormatter:", "parse", "Lorg.joda.time.YearMonth;", 0x9, NULL, NULL },
    { "fromCalendarFieldsWithJavaUtilCalendar:", "fromCalendarFields", "Lorg.joda.time.YearMonth;", 0x9, NULL, NULL },
    { "fromDateFieldsWithJavaUtilDate:", "fromDateFields", "Lorg.joda.time.YearMonth;", 0x9, NULL, NULL },
    { "init", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithOrgJodaTimeDateTimeZone:", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithOrgJodaTimeChronology:", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithLong:", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithLong:withOrgJodaTimeChronology:", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithId:", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithId:withOrgJodaTimeChronology:", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithInt:withInt:", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithInt:withInt:withOrgJodaTimeChronology:", "YearMonth", NULL, 0x1, NULL, NULL },
    { "initWithOrgJodaTimeYearMonth:withIntArray:", "YearMonth", NULL, 0x0, NULL, NULL },
    { "initWithOrgJodaTimeYearMonth:withOrgJodaTimeChronology:", "YearMonth", NULL, 0x0, NULL, NULL },
    { "readResolve", NULL, "Ljava.lang.Object;", 0x2, NULL, NULL },
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "getFieldWithInt:withOrgJodaTimeChronology:", "getField", "Lorg.joda.time.DateTimeField;", 0x4, NULL, NULL },
    { "getFieldTypeWithInt:", "getFieldType", "Lorg.joda.time.DateTimeFieldType;", 0x1, NULL, NULL },
    { "getFieldTypes", NULL, "[Lorg.joda.time.DateTimeFieldType;", 0x1, NULL, NULL },
    { "withChronologyRetainFieldsWithOrgJodaTimeChronology:", "withChronologyRetainFields", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "withFieldWithOrgJodaTimeDateTimeFieldType:withInt:", "withField", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "withFieldAddedWithOrgJodaTimeDurationFieldType:withInt:", "withFieldAdded", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "withPeriodAddedWithOrgJodaTimeReadablePeriod:withInt:", "withPeriodAdded", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "plusWithOrgJodaTimeReadablePeriod:", "plus", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "plusYearsWithInt:", "plusYears", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "plusMonthsWithInt:", "plusMonths", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "minusWithOrgJodaTimeReadablePeriod:", "minus", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "minusYearsWithInt:", "minusYears", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "minusMonthsWithInt:", "minusMonths", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "toLocalDateWithInt:", "toLocalDate", "Lorg.joda.time.LocalDate;", 0x1, NULL, NULL },
    { "toInterval", NULL, "Lorg.joda.time.Interval;", 0x1, NULL, NULL },
    { "toIntervalWithOrgJodaTimeDateTimeZone:", "toInterval", "Lorg.joda.time.Interval;", 0x1, NULL, NULL },
    { "getYear", NULL, "I", 0x1, NULL, NULL },
    { "getMonthOfYear", NULL, "I", 0x1, NULL, NULL },
    { "withYearWithInt:", "withYear", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "withMonthOfYearWithInt:", "withMonthOfYear", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "propertyWithOrgJodaTimeDateTimeFieldType:", "property", "Lorg.joda.time.YearMonth$Property;", 0x1, NULL, NULL },
    { "year", NULL, "Lorg.joda.time.YearMonth$Property;", 0x1, NULL, NULL },
    { "monthOfYear", NULL, "Lorg.joda.time.YearMonth$Property;", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "toStringWithNSString:", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "toStringWithNSString:withJavaUtilLocale:", "toString", "Ljava.lang.String;", 0x1, "Ljava.lang.IllegalArgumentException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgJodaTimeYearMonth_serialVersionUID },
    { "FIELD_TYPES", "FIELD_TYPES", 0x1a, "[Lorg.joda.time.DateTimeFieldType;", &OrgJodaTimeYearMonth_FIELD_TYPES, NULL, .constantValue.asLong = 0 },
    { "YEAR", "YEAR", 0x19, "I", NULL, NULL, .constantValue.asInt = OrgJodaTimeYearMonth_YEAR },
    { "MONTH_OF_YEAR", "MONTH_OF_YEAR", 0x19, "I", NULL, NULL, .constantValue.asInt = OrgJodaTimeYearMonth_MONTH_OF_YEAR },
  };
  static const char *inner_classes[] = {"Lorg.joda.time.YearMonth$Property;"};
  static const J2ObjcClassInfo _OrgJodaTimeYearMonth = { 2, "YearMonth", "org.joda.time", NULL, 0x11, 46, methods, 4, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_OrgJodaTimeYearMonth;
}

@end

OrgJodaTimeYearMonth *OrgJodaTimeYearMonth_now() {
  OrgJodaTimeYearMonth_initialize();
  return create_OrgJodaTimeYearMonth_init();
}

OrgJodaTimeYearMonth *OrgJodaTimeYearMonth_nowWithOrgJodaTimeDateTimeZone_(OrgJodaTimeDateTimeZone *zone) {
  OrgJodaTimeYearMonth_initialize();
  if (zone == nil) {
    @throw create_JavaLangNullPointerException_initWithNSString_(@"Zone must not be null");
  }
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeDateTimeZone_(zone);
}

OrgJodaTimeYearMonth *OrgJodaTimeYearMonth_nowWithOrgJodaTimeChronology_(OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth_initialize();
  if (chronology == nil) {
    @throw create_JavaLangNullPointerException_initWithNSString_(@"Chronology must not be null");
  }
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeChronology_(chronology);
}

OrgJodaTimeYearMonth *OrgJodaTimeYearMonth_parseWithNSString_(NSString *str) {
  OrgJodaTimeYearMonth_initialize();
  return OrgJodaTimeYearMonth_parseWithNSString_withOrgJodaTimeFormatDateTimeFormatter_(str, OrgJodaTimeFormatISODateTimeFormat_localDateParser());
}

OrgJodaTimeYearMonth *OrgJodaTimeYearMonth_parseWithNSString_withOrgJodaTimeFormatDateTimeFormatter_(NSString *str, OrgJodaTimeFormatDateTimeFormatter *formatter) {
  OrgJodaTimeYearMonth_initialize();
  OrgJodaTimeLocalDate *date = [((OrgJodaTimeFormatDateTimeFormatter *) nil_chk(formatter)) parseLocalDateWithNSString:str];
  return create_OrgJodaTimeYearMonth_initWithInt_withInt_([((OrgJodaTimeLocalDate *) nil_chk(date)) getYear], [date getMonthOfYear]);
}

OrgJodaTimeYearMonth *OrgJodaTimeYearMonth_fromCalendarFieldsWithJavaUtilCalendar_(JavaUtilCalendar *calendar) {
  OrgJodaTimeYearMonth_initialize();
  if (calendar == nil) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"The calendar must not be null");
  }
  return create_OrgJodaTimeYearMonth_initWithInt_withInt_([((JavaUtilCalendar *) nil_chk(calendar)) getWithInt:JavaUtilCalendar_YEAR], [calendar getWithInt:JavaUtilCalendar_MONTH] + 1);
}

OrgJodaTimeYearMonth *OrgJodaTimeYearMonth_fromDateFieldsWithJavaUtilDate_(JavaUtilDate *date) {
  OrgJodaTimeYearMonth_initialize();
  if (date == nil) {
    @throw create_JavaLangIllegalArgumentException_initWithNSString_(@"The date must not be null");
  }
  return create_OrgJodaTimeYearMonth_initWithInt_withInt_([((JavaUtilDate *) nil_chk(date)) getYear] + 1900, [date getMonth] + 1);
}

void OrgJodaTimeYearMonth_init(OrgJodaTimeYearMonth *self) {
  OrgJodaTimeBaseBasePartial_init(self);
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_init() {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_init(self);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_init() {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_init(self);
  return self;
}

void OrgJodaTimeYearMonth_initWithOrgJodaTimeDateTimeZone_(OrgJodaTimeYearMonth *self, OrgJodaTimeDateTimeZone *zone) {
  OrgJodaTimeBaseBasePartial_initWithOrgJodaTimeChronology_(self, OrgJodaTimeChronoISOChronology_getInstanceWithOrgJodaTimeDateTimeZone_(zone));
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithOrgJodaTimeDateTimeZone_(OrgJodaTimeDateTimeZone *zone) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithOrgJodaTimeDateTimeZone_(self, zone);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithOrgJodaTimeDateTimeZone_(OrgJodaTimeDateTimeZone *zone) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithOrgJodaTimeDateTimeZone_(self, zone);
  return self;
}

void OrgJodaTimeYearMonth_initWithOrgJodaTimeChronology_(OrgJodaTimeYearMonth *self, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeBaseBasePartial_initWithOrgJodaTimeChronology_(self, chronology);
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithOrgJodaTimeChronology_(OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithOrgJodaTimeChronology_(self, chronology);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithOrgJodaTimeChronology_(OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithOrgJodaTimeChronology_(self, chronology);
  return self;
}

void OrgJodaTimeYearMonth_initWithLong_(OrgJodaTimeYearMonth *self, jlong instant) {
  OrgJodaTimeBaseBasePartial_initWithLong_(self, instant);
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithLong_(jlong instant) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithLong_(self, instant);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithLong_(jlong instant) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithLong_(self, instant);
  return self;
}

void OrgJodaTimeYearMonth_initWithLong_withOrgJodaTimeChronology_(OrgJodaTimeYearMonth *self, jlong instant, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeBaseBasePartial_initWithLong_withOrgJodaTimeChronology_(self, instant, chronology);
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithLong_withOrgJodaTimeChronology_(jlong instant, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithLong_withOrgJodaTimeChronology_(self, instant, chronology);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithLong_withOrgJodaTimeChronology_(jlong instant, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithLong_withOrgJodaTimeChronology_(self, instant, chronology);
  return self;
}

void OrgJodaTimeYearMonth_initWithId_(OrgJodaTimeYearMonth *self, id instant) {
  OrgJodaTimeBaseBasePartial_initWithId_withOrgJodaTimeChronology_withOrgJodaTimeFormatDateTimeFormatter_(self, instant, nil, OrgJodaTimeFormatISODateTimeFormat_localDateParser());
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithId_(id instant) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithId_(self, instant);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithId_(id instant) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithId_(self, instant);
  return self;
}

void OrgJodaTimeYearMonth_initWithId_withOrgJodaTimeChronology_(OrgJodaTimeYearMonth *self, id instant, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeBaseBasePartial_initWithId_withOrgJodaTimeChronology_withOrgJodaTimeFormatDateTimeFormatter_(self, instant, OrgJodaTimeDateTimeUtils_getChronologyWithOrgJodaTimeChronology_(chronology), OrgJodaTimeFormatISODateTimeFormat_localDateParser());
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithId_withOrgJodaTimeChronology_(id instant, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithId_withOrgJodaTimeChronology_(self, instant, chronology);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithId_withOrgJodaTimeChronology_(id instant, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithId_withOrgJodaTimeChronology_(self, instant, chronology);
  return self;
}

void OrgJodaTimeYearMonth_initWithInt_withInt_(OrgJodaTimeYearMonth *self, jint year, jint monthOfYear) {
  OrgJodaTimeYearMonth_initWithInt_withInt_withOrgJodaTimeChronology_(self, year, monthOfYear, nil);
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithInt_withInt_(jint year, jint monthOfYear) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithInt_withInt_(self, year, monthOfYear);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithInt_withInt_(jint year, jint monthOfYear) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithInt_withInt_(self, year, monthOfYear);
  return self;
}

void OrgJodaTimeYearMonth_initWithInt_withInt_withOrgJodaTimeChronology_(OrgJodaTimeYearMonth *self, jint year, jint monthOfYear, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeBaseBasePartial_initWithIntArray_withOrgJodaTimeChronology_(self, [IOSIntArray arrayWithInts:(jint[]){ year, monthOfYear } count:2], chronology);
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithInt_withInt_withOrgJodaTimeChronology_(jint year, jint monthOfYear, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithInt_withInt_withOrgJodaTimeChronology_(self, year, monthOfYear, chronology);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithInt_withInt_withOrgJodaTimeChronology_(jint year, jint monthOfYear, OrgJodaTimeChronology *chronology) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithInt_withInt_withOrgJodaTimeChronology_(self, year, monthOfYear, chronology);
  return self;
}

void OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(OrgJodaTimeYearMonth *self, OrgJodaTimeYearMonth *partial, IOSIntArray *values) {
  OrgJodaTimeBaseBasePartial_initWithOrgJodaTimeBaseBasePartial_withIntArray_(self, partial, values);
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(OrgJodaTimeYearMonth *partial, IOSIntArray *values) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(self, partial, values);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(OrgJodaTimeYearMonth *partial, IOSIntArray *values) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(self, partial, values);
  return self;
}

void OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withOrgJodaTimeChronology_(OrgJodaTimeYearMonth *self, OrgJodaTimeYearMonth *partial, OrgJodaTimeChronology *chrono) {
  OrgJodaTimeBaseBasePartial_initWithOrgJodaTimeBaseBasePartial_withOrgJodaTimeChronology_(self, partial, chrono);
}

OrgJodaTimeYearMonth *new_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withOrgJodaTimeChronology_(OrgJodaTimeYearMonth *partial, OrgJodaTimeChronology *chrono) {
  OrgJodaTimeYearMonth *self = [OrgJodaTimeYearMonth alloc];
  OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withOrgJodaTimeChronology_(self, partial, chrono);
  return self;
}

OrgJodaTimeYearMonth *create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withOrgJodaTimeChronology_(OrgJodaTimeYearMonth *partial, OrgJodaTimeChronology *chrono) {
  OrgJodaTimeYearMonth *self = [[OrgJodaTimeYearMonth alloc] autorelease];
  OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withOrgJodaTimeChronology_(self, partial, chrono);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgJodaTimeYearMonth)

@implementation OrgJodaTimeYearMonth_Property

- (instancetype)initWithOrgJodaTimeYearMonth:(OrgJodaTimeYearMonth *)partial
                                     withInt:(jint)fieldIndex {
  OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(self, partial, fieldIndex);
  return self;
}

- (OrgJodaTimeDateTimeField *)getField {
  return [((OrgJodaTimeYearMonth *) nil_chk(iBase_)) getFieldWithInt:iFieldIndex_];
}

- (id<OrgJodaTimeReadablePartial>)getReadablePartial {
  return iBase_;
}

- (OrgJodaTimeYearMonth *)getYearMonth {
  return iBase_;
}

- (jint)get {
  return [((OrgJodaTimeYearMonth *) nil_chk(iBase_)) getValueWithInt:iFieldIndex_];
}

- (OrgJodaTimeYearMonth *)addToCopyWithInt:(jint)valueToAdd {
  IOSIntArray *newValues = [((OrgJodaTimeYearMonth *) nil_chk(iBase_)) getValues];
  newValues = [((OrgJodaTimeDateTimeField *) nil_chk([self getField])) addWithOrgJodaTimeReadablePartial:iBase_ withInt:iFieldIndex_ withIntArray:newValues withInt:valueToAdd];
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(iBase_, newValues);
}

- (OrgJodaTimeYearMonth *)addWrapFieldToCopyWithInt:(jint)valueToAdd {
  IOSIntArray *newValues = [((OrgJodaTimeYearMonth *) nil_chk(iBase_)) getValues];
  newValues = [((OrgJodaTimeDateTimeField *) nil_chk([self getField])) addWrapFieldWithOrgJodaTimeReadablePartial:iBase_ withInt:iFieldIndex_ withIntArray:newValues withInt:valueToAdd];
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(iBase_, newValues);
}

- (OrgJodaTimeYearMonth *)setCopyWithInt:(jint)value {
  IOSIntArray *newValues = [((OrgJodaTimeYearMonth *) nil_chk(iBase_)) getValues];
  newValues = [((OrgJodaTimeDateTimeField *) nil_chk([self getField])) setWithOrgJodaTimeReadablePartial:iBase_ withInt:iFieldIndex_ withIntArray:newValues withInt:value];
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(iBase_, newValues);
}

- (OrgJodaTimeYearMonth *)setCopyWithNSString:(NSString *)text
                           withJavaUtilLocale:(JavaUtilLocale *)locale {
  IOSIntArray *newValues = [((OrgJodaTimeYearMonth *) nil_chk(iBase_)) getValues];
  newValues = [((OrgJodaTimeDateTimeField *) nil_chk([self getField])) setWithOrgJodaTimeReadablePartial:iBase_ withInt:iFieldIndex_ withIntArray:newValues withNSString:text withJavaUtilLocale:locale];
  return create_OrgJodaTimeYearMonth_initWithOrgJodaTimeYearMonth_withIntArray_(iBase_, newValues);
}

- (OrgJodaTimeYearMonth *)setCopyWithNSString:(NSString *)text {
  return [self setCopyWithNSString:text withJavaUtilLocale:nil];
}

- (void)dealloc {
  RELEASE_(iBase_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithOrgJodaTimeYearMonth:withInt:", "Property", NULL, 0x0, NULL, NULL },
    { "getField", NULL, "Lorg.joda.time.DateTimeField;", 0x1, NULL, NULL },
    { "getReadablePartial", NULL, "Lorg.joda.time.ReadablePartial;", 0x4, NULL, NULL },
    { "getYearMonth", NULL, "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "get", NULL, "I", 0x1, NULL, NULL },
    { "addToCopyWithInt:", "addToCopy", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "addWrapFieldToCopyWithInt:", "addWrapFieldToCopy", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "setCopyWithInt:", "setCopy", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "setCopyWithNSString:withJavaUtilLocale:", "setCopy", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
    { "setCopyWithNSString:", "setCopy", "Lorg.joda.time.YearMonth;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "serialVersionUID", 0x1a, "J", NULL, NULL, .constantValue.asLong = OrgJodaTimeYearMonth_Property_serialVersionUID },
    { "iBase_", NULL, 0x12, "Lorg.joda.time.YearMonth;", NULL, NULL, .constantValue.asLong = 0 },
    { "iFieldIndex_", NULL, 0x12, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _OrgJodaTimeYearMonth_Property = { 2, "Property", "org.joda.time", "YearMonth", 0x9, 10, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_OrgJodaTimeYearMonth_Property;
}

@end

void OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(OrgJodaTimeYearMonth_Property *self, OrgJodaTimeYearMonth *partial, jint fieldIndex) {
  OrgJodaTimeFieldAbstractPartialFieldProperty_init(self);
  JreStrongAssign(&self->iBase_, partial);
  self->iFieldIndex_ = fieldIndex;
}

OrgJodaTimeYearMonth_Property *new_OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(OrgJodaTimeYearMonth *partial, jint fieldIndex) {
  OrgJodaTimeYearMonth_Property *self = [OrgJodaTimeYearMonth_Property alloc];
  OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(self, partial, fieldIndex);
  return self;
}

OrgJodaTimeYearMonth_Property *create_OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(OrgJodaTimeYearMonth *partial, jint fieldIndex) {
  OrgJodaTimeYearMonth_Property *self = [[OrgJodaTimeYearMonth_Property alloc] autorelease];
  OrgJodaTimeYearMonth_Property_initWithOrgJodaTimeYearMonth_withInt_(self, partial, fieldIndex);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgJodaTimeYearMonth_Property)
