//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/chrono/BasicFixedMonthChronology.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeChronoBasicFixedMonthChronology_INCLUDE_ALL")
#ifdef OrgJodaTimeChronoBasicFixedMonthChronology_RESTRICT
#define OrgJodaTimeChronoBasicFixedMonthChronology_INCLUDE_ALL 0
#else
#define OrgJodaTimeChronoBasicFixedMonthChronology_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeChronoBasicFixedMonthChronology_RESTRICT

#if !defined (OrgJodaTimeChronoBasicFixedMonthChronology_) && (OrgJodaTimeChronoBasicFixedMonthChronology_INCLUDE_ALL || defined(OrgJodaTimeChronoBasicFixedMonthChronology_INCLUDE))
#define OrgJodaTimeChronoBasicFixedMonthChronology_

#define OrgJodaTimeChronoBasicChronology_RESTRICT 1
#define OrgJodaTimeChronoBasicChronology_INCLUDE 1
#include "org/joda/time/chrono/BasicChronology.h"

@class OrgJodaTimeChronology;

@interface OrgJodaTimeChronoBasicFixedMonthChronology : OrgJodaTimeChronoBasicChronology

#pragma mark Package-Private

- (instancetype)initWithOrgJodaTimeChronology:(OrgJodaTimeChronology *)base
                                       withId:(id)param
                                      withInt:(jint)minDaysInFirstWeek;

- (jlong)getAverageMillisPerMonth;

- (jlong)getAverageMillisPerYear;

- (jlong)getAverageMillisPerYearDividedByTwo;

- (jint)getDayOfMonthWithLong:(jlong)millis;

- (jint)getDaysInMonthMax;

- (jint)getDaysInMonthMaxWithInt:(jint)month;

- (jint)getDaysInYearMonthWithInt:(jint)year
                          withInt:(jint)month;

- (jint)getMaxMonth;

- (jint)getMonthOfYearWithLong:(jlong)millis;

- (jint)getMonthOfYearWithLong:(jlong)millis
                       withInt:(jint)year;

- (jlong)getTotalMillisByYearMonthWithInt:(jint)year
                                  withInt:(jint)month;

- (jlong)getYearDifferenceWithLong:(jlong)minuendInstant
                          withLong:(jlong)subtrahendInstant;

- (jboolean)isLeapYearWithInt:(jint)year;

- (jlong)setYearWithLong:(jlong)instant
                 withInt:(jint)year;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJodaTimeChronoBasicFixedMonthChronology)

inline jint OrgJodaTimeChronoBasicFixedMonthChronology_get_MONTH_LENGTH();
#define OrgJodaTimeChronoBasicFixedMonthChronology_MONTH_LENGTH 30
J2OBJC_STATIC_FIELD_CONSTANT(OrgJodaTimeChronoBasicFixedMonthChronology, MONTH_LENGTH, jint)

inline jlong OrgJodaTimeChronoBasicFixedMonthChronology_get_MILLIS_PER_YEAR();
#define OrgJodaTimeChronoBasicFixedMonthChronology_MILLIS_PER_YEAR 31557600000LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgJodaTimeChronoBasicFixedMonthChronology, MILLIS_PER_YEAR, jlong)

inline jlong OrgJodaTimeChronoBasicFixedMonthChronology_get_MILLIS_PER_MONTH();
#define OrgJodaTimeChronoBasicFixedMonthChronology_MILLIS_PER_MONTH 2592000000LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgJodaTimeChronoBasicFixedMonthChronology, MILLIS_PER_MONTH, jlong)

FOUNDATION_EXPORT void OrgJodaTimeChronoBasicFixedMonthChronology_initWithOrgJodaTimeChronology_withId_withInt_(OrgJodaTimeChronoBasicFixedMonthChronology *self, OrgJodaTimeChronology *base, id param, jint minDaysInFirstWeek);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeChronoBasicFixedMonthChronology)

#endif

#pragma pop_macro("OrgJodaTimeChronoBasicFixedMonthChronology_INCLUDE_ALL")
