//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/chrono/GJLocaleSymbols.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeChronoGJLocaleSymbols_INCLUDE_ALL")
#ifdef OrgJodaTimeChronoGJLocaleSymbols_RESTRICT
#define OrgJodaTimeChronoGJLocaleSymbols_INCLUDE_ALL 0
#else
#define OrgJodaTimeChronoGJLocaleSymbols_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeChronoGJLocaleSymbols_RESTRICT

#if !defined (OrgJodaTimeChronoGJLocaleSymbols_) && (OrgJodaTimeChronoGJLocaleSymbols_INCLUDE_ALL || defined(OrgJodaTimeChronoGJLocaleSymbols_INCLUDE))
#define OrgJodaTimeChronoGJLocaleSymbols_

@class JavaUtilLocale;

@interface OrgJodaTimeChronoGJLocaleSymbols : NSObject

#pragma mark Public

- (jint)dayOfWeekTextToValueWithNSString:(NSString *)text;

- (NSString *)dayOfWeekValueToShortTextWithInt:(jint)value;

- (NSString *)dayOfWeekValueToTextWithInt:(jint)value;

- (jint)eraTextToValueWithNSString:(NSString *)text;

- (NSString *)eraValueToTextWithInt:(jint)value;

- (jint)getDayOfWeekMaxShortTextLength;

- (jint)getDayOfWeekMaxTextLength;

- (jint)getEraMaxTextLength;

- (jint)getHalfdayMaxTextLength;

- (jint)getMonthMaxShortTextLength;

- (jint)getMonthMaxTextLength;

- (jint)halfdayTextToValueWithNSString:(NSString *)text;

- (NSString *)halfdayValueToTextWithInt:(jint)value;

- (jint)monthOfYearTextToValueWithNSString:(NSString *)text;

- (NSString *)monthOfYearValueToShortTextWithInt:(jint)value;

- (NSString *)monthOfYearValueToTextWithInt:(jint)value;

#pragma mark Package-Private

+ (OrgJodaTimeChronoGJLocaleSymbols *)forLocaleWithJavaUtilLocale:(JavaUtilLocale *)locale;

@end

J2OBJC_STATIC_INIT(OrgJodaTimeChronoGJLocaleSymbols)

FOUNDATION_EXPORT OrgJodaTimeChronoGJLocaleSymbols *OrgJodaTimeChronoGJLocaleSymbols_forLocaleWithJavaUtilLocale_(JavaUtilLocale *locale);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeChronoGJLocaleSymbols)

#endif

#pragma pop_macro("OrgJodaTimeChronoGJLocaleSymbols_INCLUDE_ALL")
