//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: joda-time/src/main/java/org/joda/time/Duration.java
//

#include "J2ObjC_header.h"

#pragma push_macro("OrgJodaTimeDuration_INCLUDE_ALL")
#ifdef OrgJodaTimeDuration_RESTRICT
#define OrgJodaTimeDuration_INCLUDE_ALL 0
#else
#define OrgJodaTimeDuration_INCLUDE_ALL 1
#endif
#undef OrgJodaTimeDuration_RESTRICT

#if !defined (OrgJodaTimeDuration_) && (OrgJodaTimeDuration_INCLUDE_ALL || defined(OrgJodaTimeDuration_INCLUDE))
#define OrgJodaTimeDuration_

#define OrgJodaTimeBaseBaseDuration_RESTRICT 1
#define OrgJodaTimeBaseBaseDuration_INCLUDE 1
#include "org/joda/time/base/BaseDuration.h"

#define OrgJodaTimeReadableDuration_RESTRICT 1
#define OrgJodaTimeReadableDuration_INCLUDE 1
#include "org/joda/time/ReadableDuration.h"

#define JavaIoSerializable_RESTRICT 1
#define JavaIoSerializable_INCLUDE 1
#include "java/io/Serializable.h"

@class OrgJodaTimeDays;
@class OrgJodaTimeHours;
@class OrgJodaTimeMinutes;
@class OrgJodaTimeSeconds;
@protocol OrgJodaTimeReadableInstant;

@interface OrgJodaTimeDuration : OrgJodaTimeBaseBaseDuration < OrgJodaTimeReadableDuration, JavaIoSerializable >

#pragma mark Public

- (instancetype)initWithLong:(jlong)duration;

- (instancetype)initWithLong:(jlong)startInstant
                    withLong:(jlong)endInstant;

- (instancetype)initWithId:(id)duration;

- (instancetype)initWithOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)start
                    withOrgJodaTimeReadableInstant:(id<OrgJodaTimeReadableInstant>)end;

- (OrgJodaTimeDuration *)dividedByWithLong:(jlong)divisor;

- (jlong)getStandardDays;

- (jlong)getStandardHours;

- (jlong)getStandardMinutes;

- (jlong)getStandardSeconds;

+ (OrgJodaTimeDuration *)millisWithLong:(jlong)millis;

- (OrgJodaTimeDuration *)minusWithLong:(jlong)amount;

- (OrgJodaTimeDuration *)minusWithOrgJodaTimeReadableDuration:(id<OrgJodaTimeReadableDuration>)amount;

- (OrgJodaTimeDuration *)multipliedByWithLong:(jlong)multiplicand;

- (OrgJodaTimeDuration *)negated;

+ (OrgJodaTimeDuration *)parseWithNSString:(NSString *)str;

- (OrgJodaTimeDuration *)plusWithLong:(jlong)amount;

- (OrgJodaTimeDuration *)plusWithOrgJodaTimeReadableDuration:(id<OrgJodaTimeReadableDuration>)amount;

+ (OrgJodaTimeDuration *)standardDaysWithLong:(jlong)days;

+ (OrgJodaTimeDuration *)standardHoursWithLong:(jlong)hours;

+ (OrgJodaTimeDuration *)standardMinutesWithLong:(jlong)minutes;

+ (OrgJodaTimeDuration *)standardSecondsWithLong:(jlong)seconds;

- (OrgJodaTimeDuration *)toDuration;

- (OrgJodaTimeDays *)toStandardDays;

- (OrgJodaTimeHours *)toStandardHours;

- (OrgJodaTimeMinutes *)toStandardMinutes;

- (OrgJodaTimeSeconds *)toStandardSeconds;

- (OrgJodaTimeDuration *)withDurationAddedWithLong:(jlong)durationToAdd
                                           withInt:(jint)scalar;

- (OrgJodaTimeDuration *)withDurationAddedWithOrgJodaTimeReadableDuration:(id<OrgJodaTimeReadableDuration>)durationToAdd
                                                                  withInt:(jint)scalar;

- (OrgJodaTimeDuration *)withMillisWithLong:(jlong)duration;

@end

J2OBJC_STATIC_INIT(OrgJodaTimeDuration)

inline OrgJodaTimeDuration *OrgJodaTimeDuration_get_ZERO();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgJodaTimeDuration *OrgJodaTimeDuration_ZERO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgJodaTimeDuration, ZERO, OrgJodaTimeDuration *)

FOUNDATION_EXPORT OrgJodaTimeDuration *OrgJodaTimeDuration_parseWithNSString_(NSString *str);

FOUNDATION_EXPORT OrgJodaTimeDuration *OrgJodaTimeDuration_standardDaysWithLong_(jlong days);

FOUNDATION_EXPORT OrgJodaTimeDuration *OrgJodaTimeDuration_standardHoursWithLong_(jlong hours);

FOUNDATION_EXPORT OrgJodaTimeDuration *OrgJodaTimeDuration_standardMinutesWithLong_(jlong minutes);

FOUNDATION_EXPORT OrgJodaTimeDuration *OrgJodaTimeDuration_standardSecondsWithLong_(jlong seconds);

FOUNDATION_EXPORT OrgJodaTimeDuration *OrgJodaTimeDuration_millisWithLong_(jlong millis);

FOUNDATION_EXPORT void OrgJodaTimeDuration_initWithLong_(OrgJodaTimeDuration *self, jlong duration);

FOUNDATION_EXPORT OrgJodaTimeDuration *new_OrgJodaTimeDuration_initWithLong_(jlong duration) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeDuration *create_OrgJodaTimeDuration_initWithLong_(jlong duration);

FOUNDATION_EXPORT void OrgJodaTimeDuration_initWithLong_withLong_(OrgJodaTimeDuration *self, jlong startInstant, jlong endInstant);

FOUNDATION_EXPORT OrgJodaTimeDuration *new_OrgJodaTimeDuration_initWithLong_withLong_(jlong startInstant, jlong endInstant) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeDuration *create_OrgJodaTimeDuration_initWithLong_withLong_(jlong startInstant, jlong endInstant);

FOUNDATION_EXPORT void OrgJodaTimeDuration_initWithOrgJodaTimeReadableInstant_withOrgJodaTimeReadableInstant_(OrgJodaTimeDuration *self, id<OrgJodaTimeReadableInstant> start, id<OrgJodaTimeReadableInstant> end);

FOUNDATION_EXPORT OrgJodaTimeDuration *new_OrgJodaTimeDuration_initWithOrgJodaTimeReadableInstant_withOrgJodaTimeReadableInstant_(id<OrgJodaTimeReadableInstant> start, id<OrgJodaTimeReadableInstant> end) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeDuration *create_OrgJodaTimeDuration_initWithOrgJodaTimeReadableInstant_withOrgJodaTimeReadableInstant_(id<OrgJodaTimeReadableInstant> start, id<OrgJodaTimeReadableInstant> end);

FOUNDATION_EXPORT void OrgJodaTimeDuration_initWithId_(OrgJodaTimeDuration *self, id duration);

FOUNDATION_EXPORT OrgJodaTimeDuration *new_OrgJodaTimeDuration_initWithId_(id duration) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJodaTimeDuration *create_OrgJodaTimeDuration_initWithId_(id duration);

J2OBJC_TYPE_LITERAL_HEADER(OrgJodaTimeDuration)

#endif

#pragma pop_macro("OrgJodaTimeDuration_INCLUDE_ALL")
